In [30]:
import pandas as pd
import numpy as np
from IPython.display import display

df = pd.read_csv('full.csv', low_memory=False)

def normalize_column(df, column_name):
    df[column_name] = df[column_name].str.normalize('NFKD').str.encode('ascii', errors='ignore').str.decode('utf-8')
    return df[column_name]

def inspect_column(df, col):
    print(f'Column: {col}')
    print(f'Unique values: {len(df[col].unique())}')
    print(f'Null values: {df[col].isna().sum()}')
    display(df[[col, 'identificador']].groupby(by=col, as_index=False).count().sort_values(by='identificador', ascending=False))

In [31]:
list(df.columns)

['identificador',
 'Me identifico',
 'Tengo',
 'Dónde estás trabajando',
 'Años de experiencia',
 'Años en el puesto actual',
 'Trabajo de',
 'Plataformas',
 'Lenguajes de programación o tecnologías.',
 'Automation o funcional?',
 'QA / Testing',
 'Bases de datos',
 '¿Tenés guardias?',
 'Cuánto cobrás por guardia',
 '¿Porcentaje, bruto o neto?',
 'Tipo de contrato',
 'Salario mensual (en tu moneda local)',
 '¿Qué tan conforme estás con tu sueldo?',
 'Recibís algún tipo de bono',
 'A qué está atado el bono',
 'Cantidad de personas en tu organización',
 'Año',
 'Semestre',
 '¿Gente a cargo?',
 'Frameworks, herramientas y librerías',
 'Nivel de estudios alcanzado',
 'Estado',
 'Carrera',
 'Realizaste cursos de especialización',
 'Años en la empresa actual',
 'Universidad',
 '¿Contribuís a proyectos open source?',
 '¿Programás como hobbie?',
 'Lenguajes de programación',
 'IDEs',
 '¿Qué SO usás en tu laptop/PC para trabajar?',
 '¿Sufriste o presenciaste situaciones de violencia laboral?',
 'Orientación sexual',
 '¿Tenés algún tipo de discapacidad?',
 '¿Sentís que esto te dificultó el conseguir trabajo?',
 'Actividad principal',
 '¿La recomendás como un buen lugar para trabajar?',
 '¿Cómo calificás las políticas de diversidad e inclusión?',
 'Pagos en dólares',
 '¿Cómo venís llevando la cuarentena?',
 '¿Tenés hijos/as menores de edad?',
 '¿Qué tipo de cuarentena hiciste / estás haciendo?',
 '¿Cambió tu situación laboral a raíz de la pandemia?',
 '¿Qué tanto sentís que te está apoyando tu empresa/organización en esta situación?',
 '¿Cómo se vio afectada tu empresa/organización?',
 'Trabajo para una empresa que no tiene oficina en mi ciudad',
 '¿Cómo venís llevando la pandemia?',
 'Sufriste o presenciaste situaciones de violencia y/o acoso por motivo de',
 '¿Considerás que en tu empresa/organización hay una marcada tendencia a escuchar más a los hombres?',
 '¿Sentís que podés ser vos en tu trabajo?',
 '¿Considerás que tenés oportunidades de crecimiento siendo quien sos dentro de tu organización?',
 '¿Sentís que alguna vez los prejuicios culturales/sociales sobre tu orientación, género, etnia o discapacidad pudieron obstaculizar el que consigas un trabajo?',
 'En el último año, en tu trabajo ¿recibiste o escuchaste comentarios que considerás inapropiados, subidos de tono y/o discriminatorios?',
 '¿Cuántas veces a la semana vas a trabajar a la oficina?',
 'Valor dólar informal semestral']

In [34]:
inspect_column(df, 'Trabajo de')

Column: Trabajo de
Unique values: 3251
Null values: 0

                                     Trabajo de  identificador
868                                   Developer          16840
2515                          SysAdmin / DevOps           2825
2516                    SysAdmin / DevOps / SRE           2778
1249                                   HelpDesk           2544
2041                                QA / Tester           1907
...                                         ...            ...
1210                          Gestión Comercial              1
1211                                 Gestión IT              1
1212            Gestión de los recursos humanos              1
1213  Gestión en universidad pública y docencia              1
3250                                   winintel              1

[3251 rows x 2 columns]

In [33]:
df['Salario mensual (en tu moneda local)']

0         27000.0
1         22000.0
2         34900.0
3         30000.0
4         42000.0
           ...
45222    107000.0
45223    119600.0
45224    165000.0
45225    113000.0
45226    210000.0
Name: Salario mensual (en tu moneda local), Length: 45227, dtype: float64

In [18]:
df['Salario mensual (en tu moneda local)']
tra

0         27000.0
1         22000.0
2         34900.0
3         30000.0
4         42000.0
           ...
45222    107000.0
45223    119600.0
45224    165000.0
45225    113000.0
45226    210000.0
Name: Salario mensual (en tu moneda local), Length: 45227, dtype: float64

In [11]:
df['Valor dólar informal semestral'].unique()

array([ 15.46 ,  15.95 ,  17.855,  22.33 ,  35.29 ,  41.45 ,  61.28 ,
        94.33 , 145.67 , 147.5  , 188.16 ])

In [14]:
df.groupby(by='Valor dólar informal semestral').count()

,identificador,Me identifico,Tengo,Dónde estás trabajando,Años de experiencia,Años en el puesto actual,Trabajo de,Plataformas,Lenguajes de programación o tecnologías.,Automation o funcional?,...,¿Cómo se vio afectada tu empresa/organización?,Trabajo para una empresa que no tiene oficina en mi ciudad,¿Cómo venís llevando la pandemia?,Sufriste o presenciaste situaciones de violencia y/o acoso por motivo de,¿Considerás que en tu empresa/organización hay una marcada tendencia a escuchar más a los hombres?,¿Sentís que podés ser vos en tu trabajo?,¿Considerás que tenés oportunidades de crecimiento siendo quien sos dentro de tu organización?,"¿Sentís que alguna vez los prejuicios culturales/sociales sobre tu orientación, género, etnia o discapacidad pudieron obstaculizar el que consigas un trabajo?","En el último año, en tu trabajo ¿recibiste o escuchaste comentarios que considerás inapropiados, subidos de tono y/o discriminatorios?",¿Cuántas veces a la semana vas a trabajar a la oficina?
Valor dólar informal semestral,,,,,,,,,,,,,,,,,,,,,
15.460,3997,3997,3997,3997,3997,3997,3997,648,1235,153,...,0,0,0,0,0,0,0,0,0,0
15.950,3927,3927,3927,3927,3927,3927,3927,3927,0,0,...,0,0,0,0,0,0,0,0,0,0
17.855,4906,4906,4906,4906,4906,4906,4906,661,2430,208,...,0,0,0,0,0,0,0,0,0,0
22.330,4366,4366,4366,4366,4366,4366,4366,552,2061,170,...,0,0,0,0,0,0,0,0,0,0
35.290,1931,1931,1931,1931,1931,1931,1931,304,1053,85,...,0,0,0,0,0,0,0,0,0,0
41.450,4481,4481,4481,4481,4481,4481,4481,3704,0,0,...,0,0,0,0,0,0,0,0,0,0
61.280,3081,3081,3081,3081,3081,3081,3081,2542,0,0,...,0,0,0,0,0,0,0,0,0,0
94.330,5980,5980,5980,5980,5980,5980,5980,4882,0,0,...,0,0,0,0,0,0,0,0,0,0
145.670,90,90,90,90,90,90,90,90,0,0,...,0,0,0,0,0,0,0,0,0,0
147.500,6225,6225,6225,5888,6225,6225,6225,6225,6225,0,...,2202,0,0,0,0,0,0,0,0,0
188.160,6243,6242,6243,6243,6243,6243,6243,6242,6242,0,...,2251,1304,2252,0,0,0,0,0,0,0

In [16]:
validation = df[df['Valor dólar informal semestral']>160]
validation.to_csv('validation.csv')
train = df[df['Valor dólar informal semestral']<160]
train.to_csv('train.csv')

,identificador,Me identifico,Tengo,Dónde estás trabajando,Años de experiencia,Años en el puesto actual,Trabajo de,Plataformas,Lenguajes de programación o tecnologías.,Automation o funcional?,...,Trabajo para una empresa que no tiene oficina en mi ciudad,¿Cómo venís llevando la pandemia?,Sufriste o presenciaste situaciones de violencia y/o acoso por motivo de,¿Considerás que en tu empresa/organización hay una marcada tendencia a escuchar más a los hombres?,¿Sentís que podés ser vos en tu trabajo?,¿Considerás que tenés oportunidades de crecimiento siendo quien sos dentro de tu organización?,"¿Sentís que alguna vez los prejuicios culturales/sociales sobre tu orientación, género, etnia o discapacidad pudieron obstaculizar el que consigas un trabajo?","En el último año, en tu trabajo ¿recibiste o escuchaste comentarios que considerás inapropiados, subidos de tono y/o discriminatorios?",¿Cuántas veces a la semana vas a trabajar a la oficina?,Valor dólar informal semestral
38984,667322c6-307c-45ed-9bde-2b4af54a7cb1,Varón Cis,28,Catamarca,3.0,3.0,Developer,Firebase,"CSS, HTML, Javascript, TypeScript",NaN,...,Trabajo para una empresa que no tiene oficina ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.16
38985,021966d1-0fee-46ce-9eea-c36a0e44692e,Varón Cis,34,Catamarca,9.0,0.0,Technical Leader,"Amazon Web Services, Linux, Windows Server",Python,NaN,...,Trabajo para una empresa que no tiene oficina ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.16
38986,7a7f4bab-f3a3-44fa-8f67-845ea88af9dd,Varón Cis,45,Catamarca,16.0,12.0,Networking,"Azure, Google Cloud Platform/App Engine, Linux...","C++, COBOL, Matlab, Python",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.16
38987,15cf2d37-38bd-421b-a88a-5dabb4ed13bb,Mujer Cis,31,Chaco,4.0,0.0,Developer,Azure,"CSS, HTML, Javascript, PHP",NaN,...,Trabajo para una empresa que no tiene oficina ...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.16
38988,cd88bef9-3d15-4904-8a6e-11692076d805,Varón Cis,30,Chaco,7.0,5.0,Developer,"Amazon Web Services, Docker, Microcontroladores","Bash/Shell, CSS, HTML, Java, Javascript, PHP, ...",NaN,...,Trabajo para una empresa que no tiene oficina ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45222,f11ac55e-a37c-45a3-af6e-11cbad1e7f28,Mujer Cis,25,Tucumán,2.0,2.0,QA / Tester,Ninguna de las anteriores,Ninguno de los anteriores,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.16
45223,36ba17c9-901c-4cad-9420-ec10a08b8d19,Varón Cis,26,Tucumán,1.0,1.0,Architect,"Amazon Web Services, Firebase, Linux","CSS, HTML, Javascript, TypeScript",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.16
45224,247bcf27-b7a1-4a74-9517-b65d6119ca40,Varón Cis,26,Tucumán,3.0,1.6,Developer,Ninguna de las anteriores,".NET, C#, CSS, HTML, Javascript, TypeScript",NaN,...,Trabajo para una empresa que no tiene oficina ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.16
45225,f7817bad-2029-4da4-bdbc-2e086b520361,Varón Cis,27,Tucumán,1.0,0.0,Developer,Amazon Web Services,"Javascript, TypeScript",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.16
45226,0f7f2351-9f7a-4d51-83b4-d9e6b9786842,Varón Cis,23,Tucumán,3.0,3.0,Developer,"Amazon Web Services, Azure, Firebase",Swift,NaN,...,Trabajo para una empresa que no tiene oficina ...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188.16

In [13]:
test = pd.read_csv('test.csv', low_memory=False)
test['Valor dólar informal semestral'].unique()

array([207.25])

In [151]:
target = 'Salario mensual (en tu moneda local)'
onehot_columns = ['Dedicación', 
                 'Tipo de contrato',
                 'Modalidad de trabajo',
                 ]
delete_columns = ['Estoy trabajando en ', 
                  'Último salario mensual  o retiro BRUTO (en tu moneda local)',
                  'Último salario mensual o retiro NETO (en tu moneda local)',
                  'Si tu sueldo está dolarizado ¿Cuál fue el último valor del dólar que tomaron?',
                  '¿Qué porcentaje o monto recibís en criptomonedas?',
                  'A qué está atado el bono',
                  '¿De qué % fue el ajuste total acumulado?',
                  '¿En qué mes fue el último ajuste? *', # potential for feature engineering
                  'Con qué beneficios contas',
                  'Trabajo de',
                  'Tiempo en el puesto actual',
                  'Plataformas que utilizas en tu puesto actual ',
                  'Lenguajes de programación o tecnologías que utilices en tu puesto actual',
                  'Bases de datos',
                  'QA / Testing',
                  'Si trabajas bajo un esquema híbrido ¿Cuántos días a la semana vas a la oficina? ',
                  'Universidad ',
                  'Si participaste de un Boot Camp, ¿qué carrera estudiaste?',
                  'Cuánto cobrás por guardia',
                  '¿Porcentaje, bruto o neto?',
                  'Tengo (edad)',
                  'Me identifico (género)'
                 ]


def clean_pipeline(df):
    # geography
    north_provinces = {'Jujuy', 'Chaco', 'Catamarca', 'Corrientes', 'Santiago del Estero', 'Tucumán', 'Misiones', 'Formosa', 'Salta'}
    x1 = {key: 'North' for key in north_provinces}
    south_provinces = {'Neuquén', 'Río Negro', 'Chubut', 'Tierra del Fuego', 'Santa Cruz'}
    x2 = {key: 'South' for key in south_provinces}
    center_provinces = {'La Rioja', 'San Juan', 'Mendoza', 'La Pampa', 'Entre Ríos', 'Santa Fe', 'San Luis'}
    x3 = {key: 'Center' for key in center_provinces}
    province_dict= {'Provincia de Buenos Aires': 'PBA', 'Ciudad Autónoma de Buenos Aires': 'CABA', 'Córdoba': 'Cordoba'}
    province_dict.update(x1)
    province_dict.update(x2)
    province_dict.update(x3)
    df['Dónde estás trabajando'] = df['Dónde estás trabajando'].map(province_dict)
    # salary
    df['salary'] = df['Último salario mensual o retiro NETO (en tu moneda local)'].str.split(',').str[0]
    df['salary'] = df['salary'].str.replace('\D+', '')
    df['salary'] = pd.to_numeric(df['salary'])
    df['salary'] = np.where(df['salary']<20000, df['salary']*260, df['salary'])
    df['salary'] = np.where(df['salary']>20000*260, 20000*260, df['salary'])
    # crypto
    df['Pagos en criptomonedas'] = np.where(df['Pagos en criptomonedas'].isna(), 0, 1)
    # bono
    bono_mapping = {'No': 0, 'Menos de un sueldo': 1, 'Un sueldo': 2, 'De uno a tres sueldos': 3, '3+ sueldos': 4}
    df['Recibís algún tipo de bono'] = df['Recibís algún tipo de bono'].map(bono_mapping)
    # salary indexing
    indexing_mapping = {'No': 0, 'Uno': 1, 'Dos': 2, 'Tres': 3, 'Más de tres': 4}
    df['¿Tuviste actualizaciones de tus ingresos laborales durante 2022? '] = df['¿Tuviste actualizaciones de tus ingresos laborales durante 2022? '].map(bono_mapping)
    df['adjustment'] = df['¿De qué % fue el ajuste total acumulado?'].str.split(',').str[0]
    df['adjustment'] = df['adjustment'].str.split('.').str[0]
    df['adjustment'] = df['adjustment'].str.replace('\D+', '')
    df['adjustment'] = pd.to_numeric(df['adjustment'])
    df['adjustment'] = np.where(df['adjustment']<100, df['adjustment'], 100)
    # benefits
    df['Con qué beneficios contas'] = normalize_column(df, 'Con qué beneficios contas')
    home_regex = 'home|remot|flex'
    vacation_regex = 'vaca'
    day_regex = 'dia|viern'
    discount_regex = 'descuen'
    reimburse_regex = 'prepag|abon'
    stock_regex = 'stock|rsu'
    df['benefit_home'] = np.where(df['Con qué beneficios contas'].str.contains(home_regex, case=False), 1, 0)
    df['benefit_vacation'] = np.where(df['Con qué beneficios contas'].str.contains(vacation_regex, case=False), 1, 0)
    df['benefit_day'] = np.where(df['Con qué beneficios contas'].str.contains(day_regex, case=False), 1, 0)
    df['benefit_discount'] = np.where(df['Con qué beneficios contas'].str.contains(discount_regex, case=False), 1, 0)
    df['benefit_stock'] = np.where(df['Con qué beneficios contas'].str.contains(stock_regex, case=False), 1, 0)
    # job post
    df['Trabajo de'] = normalize_column(df, 'Trabajo de')
    admin_regex = 'admin'
    manager_regex = 'manager'
    agile_regex = 'agile'
    analyst_regex = 'anal'
    data_regex = 'data|ML|machine|DBA'
    engineer_regex = 'ingen|engine'
    support_regex = 'suppor|apoy|sopor|help'
    qa_regex = 'qa|test'
    dev_regex = 'dev|desarr'
    designer_regex = 'disen|desig'
    lead_regex = 'lead|CTO|C-level|C-suite'
    df['job_admin'] = np.where(df['Trabajo de'].str.contains(admin_regex, case=False), 1, 0)
    df['job_manager'] = np.where(df['Trabajo de'].str.contains(manager_regex, case=False), 1, 0)
    df['job_agile'] = np.where(df['Trabajo de'].str.contains(agile_regex, case=False), 1, 0)
    df['job_analyst'] = np.where(df['Trabajo de'].str.contains(analyst_regex, case=False), 1, 0)
    df['job_data'] = np.where(df['Trabajo de'].str.contains(data_regex, case=False), 1, 0)
    df['job_engineer'] = np.where(df['Trabajo de'].str.contains(engineer_regex, case=False), 1, 0)
    df['job_support'] = np.where(df['Trabajo de'].str.contains(support_regex, case=False), 1, 0)
    df['job_qa'] = np.where(df['Trabajo de'].str.contains(qa_regex, case=False), 1, 0)
    df['job_dev'] = np.where(df['Trabajo de'].str.contains(dev_regex, case=False), 1, 0)
    df['job_designer'] = np.where(df['Trabajo de'].str.contains(designer_regex, case=False), 1, 0)
    # job_lead can be inferred from number of subordinates better
    # df['job_lead'] = np.where(df['Trabajo de'].str.contains(lead_regex, case=False), 1, 0)
    # experience
    df['Años de experiencia'] = df['Años de experiencia'].str.split('.').str[0]
    df['Años de experiencia'] = pd.to_numeric(df['Años de experiencia'].str.split(',').str[0].str.replace('\D+', ''))
    df['Años de experiencia'] = pd.cut(df['Años de experiencia'], [-1, 2, 5, 10, 100000], labels=False , retbins=True, right=True)[0]
    df['Antigüedad en la empresa actual'] = df['Antigüedad en la empresa actual'].str.split('.').str[0]
    df['Antigüedad en la empresa actual'] = pd.to_numeric(df['Antigüedad en la empresa actual'].str.split(',').str[0].str.replace('\D+', ''))
    df['Antigüedad en la empresa actual'] = pd.cut(df['Antigüedad en la empresa actual'], [-1, 1, 3, 5, 100000], labels=False , retbins=True, right=True)[0]
    # subordinates
    df['¿Cuántas personas a cargo tenés? '] = pd.to_numeric(df['¿Cuántas personas a cargo tenés? '].str.replace('\D+', ''))
    df['¿Cuántas personas a cargo tenés? '] = pd.cut(df['¿Cuántas personas a cargo tenés? '], [-1, 0, 5, 20, 100000], labels=False , retbins=True, right=True)[0]
    # platforms
    df['Plataformas que utilizas en tu puesto actual '] = df['Plataformas que utilizas en tu puesto actual '].fillna('Ninguna de las anteriores')
    df['Plataformas que utilizas en tu puesto actual '] = normalize_column(df, 'Plataformas que utilizas en tu puesto actual ')
    cloud_regex = 'amazon|aws|cloud|azure|ocean|gcp'
    wind_regex = 'wind|micros'
    db_regex = 'sql|terad|databr|fireba|query|mongo'
    bi_regex = 'tableau|powerbi|looker'
    jira_regex = 'jira|atlas'
    linux_regex = 'linux|debian|redhat|ubuntu|centos'
    df['platform_cloud'] = np.where(df['Plataformas que utilizas en tu puesto actual '].str.contains(cloud_regex, case=False), 1, 0)
    df['platform_wind'] = np.where(df['Plataformas que utilizas en tu puesto actual '].str.contains(wind_regex, case=False), 1, 0)
    df['platform_db'] = np.where(df['Plataformas que utilizas en tu puesto actual '].str.contains(db_regex, case=False), 1, 0)
    df['platform_bi'] = np.where(df['Plataformas que utilizas en tu puesto actual '].str.contains(bi_regex, case=False), 1, 0)
    df['platform_jira'] = np.where(df['Plataformas que utilizas en tu puesto actual '].str.contains(jira_regex, case=False), 1, 0)
    df['platform_linux'] = np.where(df['Plataformas que utilizas en tu puesto actual '].str.contains(linux_regex, case=False), 1, 0)
    # languages
    df['Lenguajes de programación o tecnologías que utilices en tu puesto actual'] = normalize_column(df, 'Lenguajes de programación o tecnologías que utilices en tu puesto actual')
    c_regex = 'assembler|C\+\+|C\#|C$|rust|smalltalk'
    stat_regex = 'SAS|julia|SSIS|R$|matlab'
    js_regex = 'javascript|ux|html|angular|react|typescript'
    python_regex = 'python'
    java_regex = 'java$|clojure|scala|kotlin|groovy'
    bash_regex = 'bash|shell|yaml'
    excel_regex = 'excel|vb|basic'
    df['lang_c'] = np.where(df['Lenguajes de programación o tecnologías que utilices en tu puesto actual'].str.contains(c_regex, case=False), 1, 0)
    df['lang_stat'] = np.where(df['Lenguajes de programación o tecnologías que utilices en tu puesto actual'].str.contains(stat_regex, case=False), 1, 0)
    df['lang_js'] = np.where(df['Lenguajes de programación o tecnologías que utilices en tu puesto actual'].str.contains(js_regex, case=False), 1, 0)
    df['lang_python'] = np.where(df['Lenguajes de programación o tecnologías que utilices en tu puesto actual'].str.contains(python_regex, case=False), 1, 0)
    df['lang_java'] = np.where(df['Lenguajes de programación o tecnologías que utilices en tu puesto actual'].str.contains(java_regex, case=False), 1, 0)
    df['lang_bash'] = np.where(df['Lenguajes de programación o tecnologías que utilices en tu puesto actual'].str.contains(bash_regex, case=False), 1, 0)
    df['lang_excel'] = np.where(df['Lenguajes de programación o tecnologías que utilices en tu puesto actual'].str.contains(excel_regex, case=False), 1, 0)
    # frameworks
    df['Frameworks, herramientas y librerías que utilices en tu puesto actual'] = df['Frameworks, herramientas y librerías que utilices en tu puesto actual'].fillna('Ninguno de los anteriores')
    df['Frameworks, herramientas y librerías que utilices en tu puesto actual'] = normalize_column(df, 'Frameworks, herramientas y librerías que utilices en tu puesto actual')
    backend_regex = 'Spring|\.net|django|node|nest|express|fast|flask|graph|hibern|laravel|rail|sqlalc|goland|go land|php'
    frontend_regex = 'react|vue|angular|js|jquery|tailwind'
    data_regex = 'spark|hadoop|sklea|pandas|numpy|spss|torch|tensor|keras|opencv|airflow'
    df['framework_backend'] = np.where(df['Frameworks, herramientas y librerías que utilices en tu puesto actual'].str.contains(backend_regex, case=False), 1, 0)
    df['framework_frontend'] = np.where(df['Frameworks, herramientas y librerías que utilices en tu puesto actual'].str.contains(frontend_regex, case=False), 1, 0)
    df['framework_data'] = np.where(df['Frameworks, herramientas y librerías que utilices en tu puesto actual'].str.contains(data_regex, case=False), 1, 0)
    # database
    df['Bases de datos'] = df['Bases de datos'].fillna('Ninguna de las anteriores')
    df['Bases de datos'] = normalize_column(df, 'Bases de datos')
    cloud_regex = 'MariaDB|oracle|postgre|sql|SOQL'
    nouse_regex = 'none|ning|no/s|ni/s'
    df['db_sql'] = np.where(df['Bases de datos'].str.contains(data_regex, case=False), 1, 0)
    df['db_nouse'] = np.where(df['Bases de datos'].str.contains(nouse_regex, case=False), 1, 0)
    # test_framework
    df['QA / Testing'] = df['QA / Testing'].fillna('Ninguna de las anteriores')
    df['QA / Testing'] = normalize_column(df, 'QA / Testing')
    notest_regex = 'none|ning|no/s|ni/s|no$'
    df['test_notests'] = np.where(df['QA / Testing'].str.contains(notest_regex, case=False), 1, 0)
    # company size
    compsize_mapping = {'1 (solamente yo)': 0, 
                    'De 11 a 50 personas': 0, 
                    'De 2 a 10 personas': 0, 
                    'De 51 a 100 personas': 1, 
                    'De 101 a 200 personas': 1,
                    'De 201 a 500 personas': 2, 
                    'De 501 a 1000 personas': 2, 
                    'De 1001 a 2000 persona': 2, 
                    'De 2001a 5000 personas': 3, 
                    'De 5001 a 10000 personas': 3,
                    'Más de 10000 personas' : 4}
    df['Cantidad de personas en tu organización'] = df['Cantidad de personas en tu organización'].map(compsize_mapping)
    # education
    education_mapping = {'Secundario': 0, 
                    'Terciario': 1, 
                    'Universitario': 2, 
                    'Posgrado/Especialización': 3, 
                    'Maestría': 3,
                    'Doctorado': 3, 
                    'Posdoctorado' : 3}
    df['Máximo nivel de estudios'] = df['Máximo nivel de estudios'].map(education_mapping)
    df['education_isnan'] = np.where(df['Máximo nivel de estudios'].isna(), 1, 0)
    education_state_mapping = {'En curso': 0, 
                    'Incompleto': 0, 
                    'Completo' : 1}
    df['Estado'] = df['Estado'].map(education_state_mapping)
    df['Carrera'] = df['Carrera'].fillna('placeholder')
    df['Carrera'] = normalize_column(df, 'Carrera')
    tech_regex = 'cien|ing|anal|infor'
    df['Carrera'] = np.where(df['Carrera'].str.contains(tech_regex, case=False), 1, 0)
    # bootcamp
    df['¿Participaste de algún Boot Camp?'] = df['¿Participaste de algún Boot Camp?'].fillna('no')
    df['¿Participaste de algún Boot Camp?'] = normalize_column(df, '¿Participaste de algún Boot Camp?')
    boot_regex = 'no$|no\.|no'
    df['¿Participaste de algún Boot Camp?'] = np.where(df['¿Participaste de algún Boot Camp?'].str.contains(boot_regex, case=False), 0, 1)
    # guardias
    df['¿Tenés guardias? '] = df['¿Tenés guardias? '].fillna('no')
    df['¿Tenés guardias? '] = normalize_column(df, '¿Tenés guardias? ')
    guardia_regex = 'si'
    df['¿Tenés guardias? '] = np.where(df['¿Tenés guardias? '].str.contains(guardia_regex, case=False), 1, 0)
    # age
    df['Tengo (edad)'] = pd.to_numeric(df['Tengo (edad)'].str.replace('\D+', ''))
    df['Tengo (edad)'] = df['Tengo (edad)'].fillna(df['Tengo (edad)'].mean())
    df['age_binned'] = pd.cut(df['Tengo (edad)'], [-1, 25, 30, 35, 45, 100000], labels=False , retbins=True, right=True)[0]
    # gender
    df['Me identifico (género)'] = normalize_column(df, 'Me identifico (género)')
    male_regex = 'varon|hombre|macho|mascul'
    female_regex = 'mujer|femen'
    df['is_male'] = np.where(df['Me identifico (género)'].str.contains(male_regex, case=False), 1, 0)
    df['is_female'] = np.where(df['Me identifico (género)'].str.contains(female_regex, case=False), 1, 0)
    df['unk'] = np.where((df['is_male']==0) & (df['is_female']==0), 1, 0)
    return df